// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvlJIBnf1SQ5UxgaYrmze3MjTT7Y-ju0',
    appId: '1:711664301913:web:b886ab6a5a4debf1ebfe48',
    messagingSenderId: '711664301913',
    projectId: 'meife-fb37e',
    authDomain: 'meife-fb37e.firebaseapp.com',
    storageBucket: 'meife-fb37e.firebasestorage.app',
    measurementId: 'G-ZR93T3DJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvceIokL-XzaBBj77zyDLyjzhrrh2D-E8',
    appId: '1:711664301913:android:00be3cf5bf2e2b76ebfe48',
    messagingSenderId: '711664301913',
    projectId: 'meife-fb37e',
    storageBucket: 'meife-fb37e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPc1xomNpWslKJ_VIgyFdUyNgdUAVA4K4',
    appId: '1:711664301913:ios:6f559e5520ee1e17ebfe48',
    messagingSenderId: '711664301913',
    projectId: 'meife-fb37e',
    storageBucket: 'meife-fb37e.firebasestorage.app',
    iosBundleId: 'com.messlife.messlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPc1xomNpWslKJ_VIgyFdUyNgdUAVA4K4',
    appId: '1:711664301913:ios:6f559e5520ee1e17ebfe48',
    messagingSenderId: '711664301913',
    projectId: 'meife-fb37e',
    storageBucket: 'meife-fb37e.firebasestorage.app',
    iosBundleId: 'com.messlife.messlife',
  );
}
